language: node_js

node_js:
  - '10'
  - '12'
  - '14'

branches:
  only:
    - master

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.19.1
  - export PATH="$HOME/.yarn/bin:$PATH"

cache:
  yarn: true
  directories:
    - 'node_modules'

script:
  - 'yarn lint'
  - 'yarn test'

jobs:
  include:
    - stage: Build
      node_js: node
      script: yarn build
    - stage: Produce Coverage
      node_js: node
      script: yarn coveralls
    - stage: codechecks
      node_js: node
      script: yarn codechecks
